#!/usr/bin/python
from optparse import OptionParser, make_option
import sys
import dbus

bus = dbus.SystemBus()

option_list = [ make_option("-p", "--path", action="store", type="string", dest="path"), ]
parser = OptionParser(option_list=option_list)

(options, args) = parser.parse_args()

if (len(args) < 1):
        print("Usage: %s <command>" % (sys.argv[0]))
        print("")
        print("  info")
        print("  powered [on/off]")
        sys.exit(1)

cmd = args[0]
if (options.path):
	path = options.path
else:
	path = "/nrf0"

props = dbus.Interface(bus.get_object("br.org.cesar.knot.nrf", path), "org.freedesktop.DBus.Properties")

if (cmd == "info"):
	print (props.GetAll("br.org.cesar.nrf.Adapter1"))
	sys.exit(0)

if (cmd == "powered"):
	print ("powered ...")
	powered1 = props.Get("br.org.cesar.nrf.Adapter1", "Powered")
	if (len(args) < 2):
		print("  Powered: %d" % powered1)
	else:
		if (args[1] == "on"):
			value = dbus.Boolean(1)
		else:
			value = dbus.Boolean(0)

		props.Set("br.org.cesar.nrf.Adapter1", "Powered", value)
		powered2 = props.Get("br.org.cesar.nrf.Adapter1", "Powered")
		print ("  Powered: %d > %d" % (powered1, powered2))

	sys.exit(0)
